export const cuisineList = [
    "American", 
    "BBQ", 
    "Breakfast", 
    "Burgers", 
    "Cafe", 
    "Chinese", 
    "Desserts", 
    "French", 
    "Greek", 
    "Healthy", 
    "Indian", 
    "Japanese", 
    "Mexican", 
    "Noodles", 
    "Organic", 
    "Pasta", 
    "Pizza", 
    "Salads", 
    "Seafood", 
    "Spanish", 
    "Steak", 
    "Sushi", 
    "Tacos", 

]